apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
spec:
  template:
     metadata:
      name: my-pod
      labels:
         app: my-app
         type: back-end
     spec:
        containers:
        - name: my-nginx
          image: nginx

  replicas: 3